### PR TITLE
update requirements

### PR DESCRIPTION
**Pull request by Akay7**
Should work just fine. There's no too much changes https://firebase.google.com/support/release-notes/admin/python

It should resolve the issue https://github.com/xtrinch/fcm-django/issues/229

### CODE REVIEW

**Comment by xtrinch** [comment]
@Akay7 Should or does? :-) This needs at least updating the readme for the minimum supported python version as its been changed

**Comment by Akay7** [comment]
> Should or does? :-) 

It works, checked with https://github.com/xtrinch/fcm-django-web-demo

> This needs at least updating the readme for the minimum supported python version as its been changed

I updated docs. Let me know if you would like I update it in another way.

**Comment by xtrinch** [comment]
Cool, thank you! I'd like to get the current master fixed for mysql in another minor version, then we can bump the major version and release this

**Review by xtrinch — APPROVED** [review]

**Comment by Akay7** [comment]
> Cool, thank you! I'd like to get the current master fixed for mysql in another minor version first, then we can bump the major version and release this

Thank you very much. It could be great if you able to merge this and mysql fix into some branch ASAP. 
Because I got both problems:
1. With poetry that unable to resolve dependencies
2. With MariaDB that unable to create too big index.

**Comment by xtrinch** [comment]
@Akay7 https://github.com/xtrinch/fcm-django/pull/238 Please check it out and LMK if that fixes the MySQL problem for you sufficiently so we can get a move on this. I was unable to tag you there :-)

**Comment by xtrinch** [comment]
I will bump the major version for this due to python compatibility

**Pull request merged**
