### PR TITLE
My solution to issues #20: How to implement multiple FCK keys

### PR DESCRIPTION
**Pull request by sdbriney**
This pull request allows the api_key to be optionally passed into the send_message query set function. This enabled you to use different FCM server keys for each call to send_message. If no api_key is specified the code will revert back to using the key in the settings file for backwards compatibility. I also had issues with running the squashed migration so I removed it.

### CODE REVIEW

**Comment by xtrinch** [comment]
OK, this looks acceptable. I believe it requires some docs updating too though. :) Will test and release version update this week.

**Comment by sdbriney** [comment]
I have put api_key as the last named parameter.

**Comment by sdbriney** [comment]
Iv had a go at updating the documentation

**Comment by xtrinch** [comment]
@sdbriney Thank you for all your effort, merged into master and released as version 0.2.11

**Pull request merged**
