### PR TITLE
Django 2 and 1  compatibility layer

### PR DESCRIPTION
**Pull request by mrcl**
Check Django version and use the correct is_authenticated syntax

### CODE REVIEW

**Comment by xtrinch** [comment]
Will test and merge if all is well.

**Comment by nadimtuhin** [comment]
need this pr 👍

**Comment by mrcl** [comment]
@nadimtuhin, you are absolutely right. Went through the code and fixed the mistakes.

**Comment by mrcl** [comment]
Sorry guys.... I was editing everything on github and left some changes without checking. I went through it and fixed the indicated mistakes. However I didn't test because I got no time right now to setup a testing environment. I believe all the changes should take care of the problem, let me know if you find anything else.

**Comment by intelligide** [comment]
It works perfectly. I need a release as soon as possible, please. 
Thanks.

**Comment by xtrinch** [comment]
Released in 0.2.14

**Pull request merged**
