### PR TITLE
Registration ID should be unique.

### PR DESCRIPTION
**Pull request by keithhackbarth**
Prevents duplicate rows and provides faster lookups.

### CODE REVIEW

**Review by xtrinch — APPROVED** [review]

**Comment by keeth** [comment]
Seems like this change requires `UPDATE_ON_DUPLICATE_REG_ID` to be set, to function as expected? Otherwise there will be a lot of duplicate key errors.

**Comment by xtrinch** [comment]
@keeth Technically, FCM should not return duplicate keys for different devices. Perhaps that property is redundant

**Comment by xtrinch** [comment]
Which version are you using?

**Comment by romatallinn** [comment]
> Which version are you using?

^1.0.14

**Comment by romatallinn** [comment]
I guess I phrased the context quite poorly. I mean, I don't send any device ids per se. And it's not throwing the error each time it's a duplicate. But for some reason, it happens regularly, and more times than would be just for a random lag.

**Comment by xtrinch** [comment]
Yeah I see your point, although probably doesnt really make sense to invest time into something that really only happens if your application is doing something wrong

**Pull request merged**
