### PR TITLE
Separate dev and test requirements

### PR DESCRIPTION
**Pull request by olzhasar**
I've started to work on writing tests for this project, but first it will be cool to make dependencies management process more convenient. This PR is an attempt to do so.
Brief overview:
- A separate `requirements_test.txt` is used to manage test dependencies that will be used for running tests locally and in CI
- A separate `requirements_dev.txt` is used to manage dev dependencies instead of the general `requirements.txt`. By adding this file we can add development only packages and they **will not** be installed when running `tox` `or cron-update` job. `requirements_test.txt` and `requirements.txt` are sourced inside so this single file will get people covered when setting up local dev enviroment.
- `djangorestframework` and `django-tastypie` are pinned in tox.ini. This is needed because in future we will probably want to run tests against different versions of those libraries to ensure compatibility
- `isort` and `black` are added to `requirements_dev.txt`. This is needed for people who use isort and black plugins in their IDEs. Pinned versions match ones from pre-commit-config.
- `pytest_watcher` and `pytest_mock` packages added for the upcoming testing work

### CODE REVIEW

**Comment by merwok** [comment]
Have you thought about using pyproject.toml and using dependency groups in there?

**Comment by olzhasar** [comment]
@merwok 
Yes, I thought about that but there was already a 'requirements.txt' file in the project, so I decided to stick to that approach.
@xtrinch what do you think about migrating to [poetry](https://python-poetry.org/docs/) for dependency management? If that works, I will update this PR accordingly.

**Comment by xtrinch** [comment]
I'd say since you already prepared it another way, it's probably more important to work on tests, we can optimize at a later stage. But ofc up to you

**Comment by olzhasar** [comment]
Agreed. I'd suggest we merge like this for now, and then handle the migration to poetry separately later.

**Review by xtrinch — APPROVED** [review]

**Comment by xtrinch** [comment]
Done, thx @olzhasar

**Pull request merged**
