### PR TITLE
Upgrade to fcm 1.4 with handling data messages

### PR DESCRIPTION
**Pull request by gonczor**
We needed support for handling data messages, thus the fork. Apart from adding support for the mentioned feature, I've taken care of the code compliance with suggestions for third-party packages for django and python projects:
 * limiting line length to 80 characters,
 * using space indentation consequently,
 * using space hanging indentations
 * other minor changes.
I know it would be nice to include some unittests so that we ensure stability of the code, but I think it should be done in other PR.

### CODE REVIEW

**Comment by xtrinch** [comment]
Agreed, unit tests would be perfect. I'll give this a test and merge if all is well.

In any case, if you're interested in helping maintain this project, I'm all for it and I can grant you project privileges.

**Comment by gonczor** [comment]
@xtrinch I am afraid I won't be able to devote to it full time, however, I will be happy to help now and then.

**Comment by xtrinch** [comment]
Alright so there's a few issues with this pull request, first is that I don't think you've given this a test, pyfcm has updated its response form since the last version used. There's a test project you can test it with: https://github.com/xtrinch/fcm-django-web-demo

Also this package did support data messages before, you can see it / test it in the test admin actions. It's only a matter of how you structure the notification. However, pyfcm does seem to provide separate functions for it, which just ensure you are not sending a title&body with the data message. I am perfectly fine with having separate functions for it in this package too, if it seems necessary.

Also, I would rather not break user's code by changing the method names, so I've changed send_messages back to send_message.

I've pushed a few fixes.

**Comment by gonczor** [comment]
Yes, I agree that breaking compatibility was a mistake. No doubts about it.

When it comes to testing the functionality, I was not able to make this code send data messages,  I have actually missed that demo, but comparing `pyfcm` and your code I found that it does not support methods I needed in my project, so I basically only wanted to support them. Possibly someone else would make use of it.

If there are any more issues you would like me to improve, just let me know, I will be happy to contribute.

**Comment by xtrinch** [comment]
I think this pull request is good to go, I'll upload and you'll see if you can make it work for you :)

**Pull request merged**
