### PR TITLE
Add tests for AbstractFCMDevice.send_message

### PR DESCRIPTION
**Pull request by olzhasar**
- Extract test settings to a separate module (`tests/test_settings.py`). This way it will be much easier to configure
- Implement tests for AbstractFCMDevice.send_message function

### CODE REVIEW

**Comment by henriklindgren** [comment]
@xtrinch Feels like we are starting to step over each others toes here. I don't really feel like having the negativity spreading from the discussion in https://github.com/xtrinch/fcm-django/pull/244, something feels off.

@olzhasar There are send_message tests in progress already in another PR overlapping what you are doing + changing the Django test config like this makes no difference. Adding a pyproject.toml makes no sense if we're keeping setup.py and requirements, unless you are bent on keeping python 3.6 much longer.

**Comment by xtrinch** [comment]
Couple of notes:
- I merged https://github.com/xtrinch/fcm-django/pull/241 so please note of the conflicts this introduced
- where are the `send_message` tests of a similar caliber already in progress? I was unable to find it. There's some overlap with https://github.com/xtrinch/fcm-django/pull/239 but nothing that couldn't be easily integrated. The more tests the better, no?
- @olzhasar Unsure about adding `pyproject.toml`, it's supposed to replace setup.py, if that's something we'd like to do, I'd like to see that in a separate PR and done properly and keep this about the tests - we need to make sure editable installs still work even after removing setup.py

We don't need to view discussions as negativity, ofc we have different opinions, I'm sure we can make all of it work together somehow :-)

**Comment by olzhasar** [comment]
@henriklindgren
I'm not sure what negativity spreading you are referring to. Something is wrong with your perception of the collaborative development process and open source in particular. Questioning decisions is a good thing and is a part of the process. This is the only way to come up with good weighed solutions.
Regarding your comments here:
- Introducing a separate `testing_settings.py` module make a lot of difference in my opinion. Software engineering involves not only writing functional code but also ensuring that it is easy to understand and manage in the future. Having a familiar settings module, similar to what you would find in a regular Django project, is much more convenient than configuring things within pytest's hook.
- `pyproject.toml` was introduced here just to include `pytest` configuration for now. We don't have to replace `setup.py` in order to have it. We can use `pytest.ini` but I don't see much difference and don't have a strong preference here. Let me know if there is a good reason not to use `pyproject.toml`

@xtrinch 
I'll resolve the conflicts, did not see [#241](https://github.com/xtrinch/fcm-django/pull/241) tbh

**Comment by olzhasar** [comment]
@xtrinch Looks OK to me:

```
Run tox
ROOT: tox-gh-actions couldn't understand the parallel option. ignoring the given option: 0
py39-django32-linux: install_deps> python -I -m pip install 'Django<3.3,>=3.2' -r requirements.txt -r requirements_test.txt
.pkg: install_requires> python -I -m pip install 'setuptools>=40.8.0' wheel
.pkg: _optional_hooks> python /opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: freeze> python -m pip freeze --all
.pkg: pip==23.1.2,setuptools==67.7.2,wheel==0.40.0
.pkg: prepare_metadata_for_build_wheel> python /opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
py39-django32-linux: install_package_deps> python -I -m pip install Django 'firebase-admin<7,>=5'
py39-django32-linux: install_package> python -I -m pip install --force-reinstall --no-deps /home/runner/work/fcm-django/fcm-django/.tox/.tmp/package/1/fcm-django-2.0.0.tar.gz
py39-django32-linux: freeze> python -m pip freeze --all
py39-django32-linux: asgiref==3.7.2,CacheControl==0.13.0,cachetools==5.3.1,certifi==2023.5.7,cffi==1.15.1,charset-normalizer==3.1.0,cryptography==41.0.1,Django==3.2.19,django-tastypie==0.14.5,djangorestframework==3.14.0,exceptiongroup==1.1.1,fcm-django @ file:///home/runner/work/fcm-django/fcm-django/.tox/.tmp/package/1/fcm-django-2.0.0.tar.gz#sha256=e3322dcbc572a2041e4006f255d1c9a338f980d0e7529a3ab891de4099e78c5f,firebase-admin==6.1.0,google-api-core==2.[11](https://github.com/xtrinch/fcm-django/actions/runs/5188507418/jobs/9352244767?pr=245#step:5:12).0,google-api-python-client==2.88.0,google-auth==2.19.1,google-auth-httplib2==0.1.0,google-cloud-core==2.3.2,google-cloud-firestore==2.11.1,google-cloud-storage==2.9.0,google-crc32c==1.5.0,google-resumable-media==2.5.0,googleapis-common-protos==1.59.0,grpcio==1.54.2,grpcio-status==1.54.2,httplib2==0.22.0,idna==3.4,iniconfig==2.0.0,msgpack==1.0.5,packaging==23.1,pip==23.1.2,pluggy==1.0.0,proto-plus==1.22.2,protobuf==4.23.2,pyasn1==0.5.0,pyasn1-modules==0.3.0,pycparser==2.21,PyJWT==2.7.0,pyparsing==3.0.9,pytest==7.3.1,pytest-django==4.5.2,pytest-mock==3.10.0,python-dateutil==2.8.2,python-mimeparse==1.6.0,pytz==2023.3,requests==2.31.0,rsa==4.9,setuptools==67.7.2,six==1.[16](https://github.com/xtrinch/fcm-django/actions/runs/5188507418/jobs/9352244767?pr=245#step:5:17).0,sqlparse==0.4.4,tomli==2.0.1,typing_extensions==4.6.3,uritemplate==4.1.1,urllib3==1.26.16,wheel==0.40.0
py39-django32-linux: tox-gh-actions couldn't understand the parallel option. ignoring the given option: 0
tox: py39-django32-linux
  py39-django32-linux: commands[0]> pytest tests
  ============================= test session starts ==============================
  platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0
  cachedir: .tox/py39-django32-linux/.pytest_cache
  django: settings: tests.testing_settings (from ini)
  rootdir: /home/runner/work/fcm-django/fcm-django
  configfile: pyproject.toml
  plugins: mock-3.10.0, django-4.5.2
  collected 7 items
  
  tests/test_models.py .......                                             [100%]
  
  ============================== 7 passed in 0.54s ===============================
```

**Comment by xtrinch** [comment]
@olzhasar What I would like to see is a report on test cases, not just files 🤔

**Comment by xtrinch** [comment]
And in the future, I'd also like a README in the tests folder with a simple explanation on how to set up & run testing locally 💡

**Comment by olzhasar** [comment]
@xtrinch 
AFAIK, `pytest` shows this kind of breakdown only if some tests failed

**Comment by olzhasar** [comment]
@xtrinch I did not get the part about `python-pytest-steps`, what exactly it will help with?

**Comment by olzhasar** [comment]
Added the `-v` flag to `tox.ini`

**Comment by olzhasar** [comment]
> @olzhasar Much better, maybe a color flag? :-) --color=yes

Once again, I don't think that relates to the current PR, do you?

**Comment by xtrinch** [comment]
No worries I can add that, doesn't warrant a separate PR

**Pull request merged**
