### PR TITLE
Update models.py

### PR DESCRIPTION
**Pull request by sthz31**
max_length of registration id is 150 which doesn't seem working so I  have increased it to 1000

### CODE REVIEW

**Comment by sthz31** [comment]
Change max_length for API key

**Comment by Andrew-Chen-Wang** [comment]
it could even go up to 4096. Maybe refer to this: https://stackoverflow.com/a/39964597 ???

**Comment by Andrew-Chen-Wang** [comment]
@sthz31 after further inspection, a notification payload is at most 4kb. So it's gotta be lower than 4kb. After reading up on this: https://stackoverflow.com/a/64902685 it would *seem* it's 163, but other comments are saying it's gotten to 317 and 326 (comments from https://stackoverflow.com/a/40572076). So idk. I definitely has to be lower than 4kb, but this varying amount of characters is kinda insane...

@xtrinch what do you think is a safe number? On https://github.com/jazzband/django-push-notifications/blob/master/push_notifications/models.py, they don't have a max value. APNS devices do which is maxed out at 200, but to service but Android and iOS, I'd assume it's something like 500...

**Comment by Andrew-Chen-Wang** [comment]
@xtrinch I think this is a good enough number. It'll never get to this point, but we also have no idea what the max length is, so this is satisfiable. For future developers, it may be necessary to run a prune command to get rid of inactive devices in case a malicious actor starts polluting the db (note I didn't check if our current view set makes a check to see the device id is valid).

**Comment by xtrinch** [comment]
Okay, sure. Well they could turn on the automatic deletion of inactive devices, don't see why one would keep those around anyway.

**Comment by xtrinch** [comment]
@sthz31 This PR is missing a migration though?

**Comment by Andrew-Chen-Wang** [comment]
> automatic deletion of inactive devices

haven't really looked at the device viewsets, but based on previous experience with other packages, anything to do with "automating deletion" of expired/inactive things is frowned upon because of spam attacks against an API endpoint which could result in accidental DOS due to that extra query.

**Comment by xtrinch** [comment]
**You** need to actually trigger notification sending for the deletion to occur, so this really couldn't trigger an accidental DOS. There's no extra queries when registering devices.

**Comment by Andrew-Chen-Wang** [comment]
hahaha after a week, I've already forgotten the code I've written. You're absolutely right :D

**Comment by Andrew-Chen-Wang** [comment]
@xtrinch btw the ReadTheDocs page needs to be updated. You could probably add a web hook from RTD so that it's automatic.

**Comment by xtrinch** [comment]
@Andrew-Chen-Wang  It looks to me as it is automatic already? It was just failing as it was trying to build with python 2.7.

**Comment by xtrinch** [comment]
I'll generate the migration file, merging

**Pull request merged**
